server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    #preferIpAddress: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
          #TODO 6 rutas para cada microservicio
        - id: m2-registro-usuario
          uri: lb://m2-registro-usuario
          predicates:
            - Path=/simulation/**
        - id: actual-registro-usuario
          uri: lb://actual-registro-usuario
          predicates:
            - Path=/register/**

        - id: m3-solicitud-credito
          uri: lb://m3-solicitud-credito
          predicates:
            - Path=/credit-request/**

        - id: m4-evaluacion-credito
          uri: lb://m4-evaluacion-credito
          predicates:
            - Path=/credit-eval/**

        - id: m5-seguimiento-solicitud
          uri: lb://m5-seguimiento-solicitud
          predicates:
            - Path=/track-request/**