server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          #TODO 6 rutas para cada microservicio
        - id: m2-registro-usuario
          uri: lb://m2-registro-usuario
          predicates:
            - Path=/m2-registro-usuario/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**