server:
  #SERVER_PORT_CLIENTS = 8090
  #PORT:0 => asignacion dinámica
  port: ${SERVER_PORT_CLIENTS}
spring:
  #DB_HOST = localhost
  #DB_PORT_CLIENTS = 5432
  #DB_DBNAME_CLIENTS = tingeso-clients-db
  #DB_USER = postgres
  #DB_PASSWORD = admin
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT_CLIENTS}/${DB_DBNAME_CLIENTS}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka