apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-registro-usuario-deployment #nombre del pod
  labels:
    app: actual-registro-usuario-deployment
spec:
  selector:
    matchLabels:
      app: actual-registro-usuario-deployment  #los 3 usan este nombre
  replicas: 1                              #existen 3 pods como replicas, para la Evaluacion puede ser 1
  template:
    metadata:
      labels:
        app: actual-registro-usuario-deployment
    spec:
      containers:
        - name: actual-registro-usuario-deployment
          image: tomasmanriquez480/actual-registro-usuario:latest
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ACTUAL
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ACTUAL
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ACTUAL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: actual-registro-usuario-service
  labels:
    app: actual-registro-usuario-service
spec:
  selector:
    app: actual-registro-usuario-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP