apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2-registro-usuario-deployment #nombre del pod
  labels:
    app: m2-registro-usuario-deployment
spec:
  selector:
    matchLabels:
      app: m2-registro-usuario-deployment  #los 3 usan este nombre
  replicas: 1                              #existen 3 pods como replicas, para la Evaluacion puede ser 1
  template:
    metadata:
      labels:
        app: m2-registro-usuario-deployment
    spec:
      containers:
        - name: m2-registro-usuario-deployment
          image: tomasmanriquez480/m2-registro-usuario:latest
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M2
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M2
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_M2
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
