apiVersion: apps/v1
kind: Deployment
metadata:
  name: m3-solicitud-credito-deployment #nombre del pod
  labels:
    app: m3-solicitud-credito-deployment
spec:
  selector:
    matchLabels:
      app: m3-solicitud-credito-deployment  #los 3 usan este nombre
  replicas: 1                              #existen 3 pods como replicas, para la Evaluacion puede ser 1
  template:
    metadata:
      labels:
        app: m3-solicitud-credito-deployment
    spec:
      containers:
        - name: m3-solicitud-credito-deployment
          image: tomasmanriquez480/m3-solicitud-credito:latest
          ports:
            - containerPort: 8092
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M3
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M3
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_M3
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: m3-solicitud-credito-service
  labels:
    app: m3-solicitud-credito-service
spec:
  selector:
    app: m3-solicitud-credito-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP