apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6-calculo-costos-totales-deployment #nombre del pod
  labels:
    app: m6-calculo-costos-totales-deployment
spec:
  selector:
    matchLabels:
      app: m6-calculo-costos-totales-deployment  #los 3 usan este nombre
  replicas: 1                              #existen 3 pods como replicas, para la Evaluacion puede ser 1
  template:
    metadata:
      labels:
        app: m6-calculo-costos-totales-deployment
    spec:
      containers:
        - name: m6-calculo-costos-totales-deployment
          image: tomasmanriquez480/m6-calculo-costos:latest
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M6
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M6
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_M6
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: m6-calculo-costos-totales-service
  labels:
    app: m6-calculo-costos-totales-service
spec:
  selector:
    app: m6-calculo-costos-totales-deployment
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 8094
  type: ClusterIP