apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  #actual-registro-usuario
  DB_HOST_ACTUAL:
  DB_PORT_ACTUAL: "5432"
  DB_DBNAME_ACTUAL: db-actual-registro-usuario
  #m2-registro-usuario
  #TODO DB_HOST_M2: #db-m2 service
  DB_PORT_M2: "5432"
  DB_DBNAME_M2: db-m2
  DB_USER_M2: "postgres"
  DB_PASSWORD_M2: "admin"
  #m3-solicitud-credito

  #m4-evaluacion-credito

  #m5-seguimiento-solicitud

  #m6-calculo-costos-totales