apiVersion: v1
kind: Secret
metadata:
  name: postgres-root-secret
type: Opaque
data:
  # TODO codificar username, password
  username: postgres
  password: admin
  # TODO ver si hace falta otro yaml para 'postgres-user-secret'