server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/tomas-manriquez/tingeso2-2024-2
          search-paths: config-data
  application:
    name: config-service
